version: '3.8'
services:
    postgres:
        image: postgres
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow

    webserver:
        image: apache/airflow
        entrypoint: ./scripts/entrypoint.sh
        deploy: 
            replicas: 1
        restart: on-failure:1
        depends_on:
            - postgres
        env_file:
            - ./airflow/.env
        volumes:
            - ./airflow/dags:/opt/airflow/dags
            - ./airflow/logs:/opt/airflow/logs
            - ./airflow/plugins:/opt/airflow/plugins
            - ./airflow/scripts:/opt/airflow/scripts
        ports:
            - "8080:8080"

    scheduler:
        image: apache/airflow
        command: scheduler
        restart: on-failure:1
        depends_on:
            - postgres
            - webserver
        env_file:
            - ./airflow/.env
        volumes:
            - ./airflow/dags:/opt/airflow/dags
            - ./airflow/logs:/opt/airflow/logs
            - ./airflow/plugins:/opt/airflow/plugins