"""jobs table

Revision ID: 7034a278fe84
Revises: 
Create Date: 2020-12-01 23:02:35.404691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7034a278fe84'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_name', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('goal', sa.String(length=255), nullable=True),
    sa.Column('data_sources', sa.String(length=255), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('company_url', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job')
    # ### end Alembic commands ###
